export const inputs = [
    {
        label: 'user',
        type: 'text',
        name: 'fullName',
        placeholder: 'Nombre completo',
        firstIcon: 'userIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'location',
        type: 'text',
        name: 'country',
        placeholder: 'Ubicación',
        firstIcon: 'locationIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'suitcase',
        type: 'text',
        name: 'ocupation',
        placeholder: 'Ocupación',
        firstIcon: 'suitcaseIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'desription',
        type: 'text',
        name: 'description',
        placeholder: 'Descripción',
        firstIcon: 'desriptionIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'habilidades',
        type: 'text',
        name: 'skills',
        placeholder: 'Habilidades',
        firstIcon: 'desriptionIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'experience',
        type: 'text',
        name: 'experience',
        placeholder: 'Experiencia laboral',
        firstIcon: 'desriptionIcon',
        startIcon: true,
        endIcon: false,
    }
]