export const inputs = [
    {
        label: 'enterprise',
        type: 'text',
        placeholder: 'Nombre de la empresa',
        firstIcon: 'enterpriseIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'location',
        type: 'text',
        placeholder: 'Ubicación',
        firstIcon: 'locationIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'suitcase',
        type: 'text',
        placeholder: 'Ocupación',
        firstIcon: 'suitcaseIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'email',
        type: 'text',
        placeholder: 'Correo electronico',
        firstIcon: 'emailIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'phone',
        type: 'text',
        placeholder: 'Número telefónico',
        firstIcon: 'phoneIcon',
        startIcon: true,
        endIcon: false,
    },
    {
        label: 'password',
        placeholder: 'Contraseña',
        firstIcon: 'passwordIcon',
        secondIcon: 'eyeIcon',
        startIcon: true,
        endIcon: true,
    },
]